import unittest
from openai_solution.roman_numbers import  roman_to_int
'''
This class was generated by ChatGTP
'''


class TestRomanToInt(unittest.TestCase):
    def test_valid_inputs(self):
        self.assertEqual(roman_to_int('I'), 1)
        self.assertEqual(roman_to_int('V'), 5)
        self.assertEqual(roman_to_int('X'), 10)
        self.assertEqual(roman_to_int('L'), 50)
        self.assertEqual(roman_to_int('C'), 100)
        self.assertEqual(roman_to_int('D'), 500)
        self.assertEqual(roman_to_int('M'), 1000)
        self.assertEqual(roman_to_int('IV'), 4)
        self.assertEqual(roman_to_int('IX'), 9)
        self.assertEqual(roman_to_int('XI'), 11)
        self.assertEqual(roman_to_int('MCMXCVI'), 1996)

    def test_invalid_inputs(self):
        self.assertRaises(KeyError, roman_to_int, 'A')
        self.assertRaises(KeyError, roman_to_int, 'AB')
        self.assertRaises(KeyError, roman_to_int, '1')
        self.assertRaises(KeyError, roman_to_int, '-1')
       # self.assertRaises(KeyError, roman_to_int, 'IIII') This test failed
       # self.assertRaises(KeyError, roman_to_int, 'VV') same here
       # self.assertRaises(KeyError, roman_to_int, 'IL') same here
       # self.assertRaises(KeyError, roman_to_int, 'IC') same here


if __name__ == '__main__':
    unittest.main()
